name: markdown-lint
on:
  push:
    paths:
      - "**.md"
  pull_request:
    paths:
      - "**.md"
jobs:
  mdl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          globs: |
            **/*.md